- package-lock.json
- server/db/models/glasses.js
- server/db/models/index.js
- server/db/models/item.js
- server/db/models/order.js
- server/db/models/user.js
Created User, Order, Glasses, & Item db models and associations
> created db models and associations

- package-lock.json
- server/api/glasses.js
- server/api/index.js
finish glasses routes:
- GET api/glasses
- GET api/glasses/:id
- POST api/glasses
- PUT api/glasses/:id
- DELETE api/glasses/:id 
** admin functionality to come later
> finish glasses routes

- package-lock.json
- server/api/users.js
created /api/users routes:
- GET '/'
- GET '/:id'
-POST '/'
-PUT '/:id'
-DELETE '/:id'
> created basic user routes

- server/api/users.js
- server/auth/index.js
> added a route to serve user orders, deleted post route for now

- client/app.js
- client/components/Glasses.js
- client/components/auth-form.js
- client/components/index.js
- client/components/user-home.js
- client/history.js
- client/routes.js
- client/store/user.js
- server/api/glasses.js
- server/api/users.js
- server/auth/google.js
- server/auth/index.js
- server/db/db.js
- server/db/models/index.js
- server/db/models/item.js
- server/db/models/order.js
- server/db/models/user.js
- server/db/models/user.spec.js
- server/index.js
- tests/client/user-home.spec.js
- tests/client/user.spec.js
- tests/server/glasses.spec.js
- tests/server/route.spec.js
- tests/server/users.spec.js
- webpack.config.js
- strengthen glasses routes
- fix local merge conflict
> strengthen glasses routes

- client/components/navbar.js
> fix merge conflict

- client/components/Glasses.js
- client/components/navbar.js
- public/style.css
Added single view link to glasses component and updated css
> Single view link

- client/components/SingleGlasses.js
- client/components/navbar.js
- client/store/index.js
- server/api/orders.js
- server/db/models/index.js
- added glassId and purchaseDate to order before creating instance
-added number of items in cart to Navbar
> fixed add to cart functionality

- client/components/Cart.js
- client/components/CofirmationPage.js
- client/routes.js
- public/style.css
Created initial confirmation page component:
- displays shipping info
- displays ordered items info
- displays order number
- add initial style component
- added initial link in cart section (only for testing, will delete)
> add confirmation page component and initial style

- client/components/User.js
- client/components/navbar.js
- client/components/user-home.js
- client/routes.js
- client/store/index.js
- client/store/users.js
- public/style.css
- script/seed.js
- server/api/users.js
Added User component that displays dashboard
- shows specialized dashboard based on whether user is admin or not
- add initial style for dashboard views
- created "users" reducer that will provide all users (for admin) on state
> add user component with basic user and admin capabilities

- client/components/Cart.js
- client/components/navbar.js
- client/store/index.js
- client/store/order.js
- package-lock.json
- package.json
- server/api/orders.js
- server/api/users.js
- server/db/models/order.js
> Finish cart#42

- client/routes.js
> travis deployed

- client/components/Checkout.js
- client/components/OrderHistory.js
- client/store/order.js
- public/style.css
Added styling to order history and added order total
> Update order history

- client/components/Checkout.js
- client/components/CheckoutForm.js
- client/components/ConfirmationPage.js
- client/components/navbar.js
- client/store/completedOrders.js
- client/store/index.js
- client/store/order.js
- client/store/user.js
- public/style.css
Confirmation Page
- add more styling for shipment details
- updates info from redux state
- shows shipment details
- shows items ordered
> Confirmation page final#66

- client/components/Cart.js
- client/components/SingleGlasses.js
- client/components/navbar.js
- client/store/order.js
- server/api/orders.js
> Finish cart

- client/components/Checkout.js
- client/components/CheckoutForm.js
- client/components/navbar.js
- client/store/glasses.js
- client/store/order.js
- client/store/user.js
- server/api/glasses.js
- server/auth/google.js
> Cart checkout fix

- tests/client/user.spec.js
> travis fix

- client/components/OrderHistory.js
- public/style.css
> styling tweaks to order history

- client/components/Cart.js
- client/components/Checkout.js
- client/components/CheckoutForm.js
- client/components/navbar.js
- public/index.html
- public/style.css
> Css fix for navbar and checkout

- client/store/completedOrders.js
- client/store/order.js
fixed confirmation page
- only shows items on confirmed order
> fix confirmation page

- client/components/Cart.js
- client/components/Homepage.js
- client/components/SingleGlasses.js
- client/components/auth-form.js
- public/style.css
> Update images buttons

- client/components/User.js
- public/style.css
> final changes css
